export { default as HomePage } from './HomePage'
export { default as AboutPage } from './AboutPage'
export { default as ContactPage } from './ContactPage'
export { default as QuotePage } from './QuotePage'
export { default as ServicesPage } from './ServicesPage'
export { default as ServiceDetailPage } from './ServiceDetailPage'
export { default as ProjectsPage } from './ProjectsPage'
